### PR TITLE
How-to guide on converting ML code from Kaggle to MLRun

### PR DESCRIPTION
**Pull request by EdmondIguazio**
A example on how to convert an ML code (from Kaggle) into MLRun.

### CODE REVIEW

**Review by Sharon-iguazio — APPROVED** [review]
I pushed doc-review edits (including renaming of the model-serving NB and the pipeline-output image file, as agreed offline with Edmond) — see commit 783ac36. @EdmondIguazio please check and confirm my edits.

**Comment by EdmondIguazio** [comment]
@Sharon-iguazio , looks fine to me

**Comment by Sharon-iguazio** [comment]
@Hedingber / @zilbermanor please merge; please also check whether the merge to be to `development` or to `0.6.x-dev`.

**Comment by zilbermanor** [comment]
@EdmondIguazio Could you please re-open with merge to 0.6.x-dev?

**Comment by EdmondIguazio** [comment]
@zilbermanor done

**Review by zilbermanor — APPROVED** [review]

**Pull request merged**
